### PR TITLE
Reduce E2E entry barriers

### LINKED ISSUE #898: E2E setup (windows)
Basically a small docu for windows/mingw installations

### Tasks

 - [ ] Mention how to install python3-pip
 - [ ] Mention on which operating system the documentation/scripts work
 - [ ] Add env variables for clean_db.py (DATABASE_URL etc)

### Something else

- [ ] Mention in the top readme that the makefile is only for fast execution of frequent tasks, for more detailed executions to look into the seperate folders readme

### PR DESCRIPTION
**Pull request by 4ydan**
Closes #898 

I did not want to overengineer this, so I did not add separate .bat scripts for windows.
I'm not really sure what the desired solution for this would be.

- Added more env variables
- Put env defaults into readme
- Mentions python and pip installation
- Hint for windows users

## Basics

- [x] I added a line to [changelog.md](/doc/changelog.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

### CODE REVIEW

**Comment by markus2330** [comment]
> I did not want to overengineer this, so I did not add separate .bat scripts for windows.

Yes, that would be too much maintenance effort.

> I'm not really sure what the desired solution for this would be.

I think it is fine as-is, let us see what @tschawax says.

**Comment by markus2330** [comment]
@4ydan please resolve conflicts, so that we can merge it.

**Comment by 4ydan** [comment]
So I did not really write a step by step guide how to install python or pip3, I think there is enough documentation out there. I just put it as pre-requisite.

**Comment by markus2330** [comment]
Thanks for maintaining the documentation and keeping it simple :heart:

**Pull request merged**
