### PR TITLE
Fix broken darkmode for LanguageSwitcher, SelectMenu & PaginatedSelectMenu 

### PR DESCRIPTION
**Pull request by hatchla**
## Basics

- [x] The PR is rebased with current master
- [x] I added a line to [changelog.md](/doc/changelog.md)
- [x] Details of what I changed are in the commit messages
- [x] References to issues, e.g. `close #X`, are in the commit messages and changelog
- [x] The buildserver is happy

## Checklist

- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## First Time Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [x] I am using [Tailwind CSS Linting](https://tailwindcss.com/blog/introducing-linting-for-tailwindcss-intellisense)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines
- [ ] I've checked conformity to requirements
- [ ] I've checked that the requirements are tested

### CODE REVIEW

**Comment by hatchla** [comment]
Branch 'docker-setup' by @horenso needs to be merged before this.

**Comment by horenso** [comment]
you could also drop the commit  of docker-setup for this pr?

**Comment by danielsteinkogler** [comment]
the code LGTM.
maybe the text color of the selected language in light mode should be white:
image

**Review by danielsteinkogler — APPROVED** [review]

**Comment by markus2330** [comment]
I agree with Daniel, text should be better readable. If it is easy, please fix it here.

CI is not yet happy: https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1229/2/pipeline

**Comment by chr-schr** [comment]
Also if the dropdown element has focus, it is a bit hard to read in dark mode (gray on gray).
image

Otherwise it LGTM 👍

**Review by chr-schr — APPROVED** [review]

**Comment by hatchla** [comment]
> I agree with Daniel, text should be better readable. If it is easy, please fix it here.
> 
> CI is not yet happy: https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-1229/2/pipeline

This I already fixed in the last commit.

**Comment by hatchla** [comment]
> Also if the dropdown element has focus, it is a bit hard to read in dark mode (gray on gray). image
> 
> Otherwise it LGTM 👍

Do you mean the "en" and "de" or which element do you mean?

**Comment by markus2330** [comment]
CI still not fixed, maybe it is another error?

**Review by horenso — APPROVED** [review]

**Comment by chr-schr** [comment]
> Do you mean the "en" and "de" or which element do you mean? @chr-schr

Yes, the 'en' in the screenshot

**Comment by hatchla** [comment]
> > Do you mean the "en" and "de" or which element do you mean? @chr-schr
> 
> Yes, the 'en' in the screenshot

TBO this has always been that way and is part of the general theme as I see it... I would leave it like it is to not get inconsistent. What do you think @markus2330?

**Comment by markus2330** [comment]
I agree. Thx for the fix! :heart:

**Pull request merged**
