### PR TITLE
#39 cleanup of unit tests

### PR DESCRIPTION
**Pull request by kitzbergerg**
## Basics

- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by kitzbergerg** [comment]
This would be an initial draft of the unit test cleanup. It seems a lot neater like this although there now is the problem that we cannot (we didn't do that before either) validate the state of the database after the test is done. Ideally we should test if something was actually removed from the database after e.g. calling the delete endpoint.
Maybe we can create a struct wrapping the helper functions.

@Benjaminimal @Bushuo @badnames Feel free to leave suggestions about how we want to handle that. You can also remove yourself as reviewers and unsubscribe if you don't fell like adding something (especially since this is in somewhat early stages)

**Comment by kitzbergerg** [comment]
> Maybe we can create a struct wrapping the helper functions so we have a
> 
> ```rust
> let test = MyTestStruct::init_db(|conn|...);
> test.run_test(|app| ...);
> test.validate_db(|conn| ...);
> ```

I'll give up on this variant. This soon gets really annoying with Traits, Futures and the likes (as `app` in this example is not a struct but just Trait bounds and I would have to define them correctly which is quite difficult).

**Comment by kitzbergerg** [comment]
@markus2330 The cleanup in that sense is now done.
I believe we should still add validation of the database's state after the tests are run. Also there are some tests missing e.g. delete for seeds. Should this be included in this PR?

**Review by markus2330 — APPROVED** [review]
LGTM, thank you for the cleanup!

**Comment by markus2330** [comment]
Unfortunately needs rebase. You can also add the new test case(s) here.

**Comment by kitzbergerg** [comment]
@markus2330 I just rebased. I would prefer to merge it as soon as possible to avoid additional merge conflicts. This PR affects every new testcase we will add in the future, so every new test case added in some other branch would lead to a conflict if this is not merged. I didn't think about that.

So I would prefer adding new tests in a separate PR to get this merged as soon as possible.

**Comment by markus2330** [comment]
Thank you for merging the master branch here! (It is different to rebasing, though.)

**Pull request merged**
