### PR TITLE
fix seeds route and add guideline

### PR DESCRIPTION
**Pull request by danielsteinkogler**
## Basics

- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

### CODE REVIEW

**Comment by danielsteinkogler** [comment]
jenkins build please

**Review by markus2330 — APPROVED** [review]
LGTM, please also invite others for review, ideally before you invite me.

**Comment by danielsteinkogler** [comment]
jenkins build please

**Review by absurd-turtle — APPROVED** [review]

**Comment by danielsteinkogler** [comment]
jenkins build please

**Comment by danielsteinkogler** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
rebasing was missing, so hopefully the flaky e2e test is now fixed (#746)

**Comment by markus2330** [comment]
@4ydan is the route maybe used somewhere in the tests? Already failing 4x

**Comment by danielsteinkogler** [comment]
i think a new test has been added after creating this PR that references on `/seeds/new`. i changed the test and hopefully all of them will pass now

**Comment by markus2330** [comment]
Superb! :heart:

**Pull request merged**
