### PR TITLE
implemented basic planting cursor icon

### PR DESCRIPTION
**Pull request by absurd-turtle**
I timeboxed the effort and implemented a basic plant icon which follows the cursor while planting.

## Basics

- [x] I added a line to [changelog.md](/doc/changelog.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

### CODE REVIEW

**Comment by markus2330** [comment]
This is perfectly as we imagined! :heart: 

Pls also make CI happy etc.

**Review by markus2330 — APPROVED** [review]

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
@4ydan E2E fail here, too.

**Review by 4ydan — APPROVED** [review]
Very nice!

**Comment by 4ydan** [comment]
E2E tests dont have a cursor, and it seems there is a problem with that.

**Comment by markus2330** [comment]
In general I am skeptical about having any difference during testing, as this makes it much harder to reason about what we actually test. But maybe it is the right thing to do for the cursor.

We could merge it for the release, revert it, and then find a proper solution for the e2e tests?

**Pull request merged**
