### PR TITLE
CI: pre-commit all files

### LINKED ISSUE #261: pre-commit run --all-files fails
@Benjaminimal should we maybe add `pre-commit run --all-files` to CI? Or just `pre-commit` after this is fixed manually?

currently on master:
```
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
mixed line ending........................................................Passed
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing doc/meetings/2023_04_11.md
Fixing frontend/src/features/seeds/components/CreateSeedForm.tsx
Fixing doc/decisions/backend_orm_crate.md
Fixing frontend/src/features/seeds/api/searchPlants.ts
Fixing doc/usecases/polyculture/review_plant_relationships.md
Fixing frontend/src/features/seeds/store/CreateSeedStore.ts

doc format...............................................................Failed
- hook id: prettier
- files were modified by this hook
benchmarks/README.md
doc/meetings/2023_03_31_frontend.md
benchmarks/package.json


frontend format..........................................................Failed
- hook id: prettier
- files were modified by this hook

frontend/src/features/seeds/components/CreateSeedForm.tsx
frontend/src/features/seeds/routes/CreateSeed.tsx
frontend/src/components/Form/PaginatedSelectMenu.tsx
frontend/src/features/seeds/api/searchPlants.ts


frontend lint............................................................Failed
- hook id: eslint
- duration: 2.74s
- exit code: 1


/home/markus/Projekte/PermaplanT/frontend/src/features/seeds/routes/CreateSeed.tsx
  10:10  warning  'useEffect' is defined but never used                           @typescript-eslint/no-unused-vars
  30:9   warning  'debouncedPlantSearchParam' is assigned a value but never used  @typescript-eslint/no-unused-vars
  59:9   warning  'onVarietyInputChange' is assigned a value but never used       @typescript-eslint/no-unused-vars
  63:9   warning  'plants' is assigned a value but never used                     @typescript-eslint/no-unused-vars

✖ 4 problems (0 errors, 4 warnings)

ESLint found too many warnings (maximum: 0).

/home/markus/Projekte/PermaplanT/frontend/src/components/Form/CreatableSelectMenu.tsx
  15:34  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  15:62  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 2 problems (0 errors, 2 warnings)

ESLint found too many warnings (maximum: 0).

/home/markus/Projekte/PermaplanT/frontend/src/tailwind.config.js
  115:1  error  'module' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)


/home/markus/Projekte/PermaplanT/frontend/src/components/Form/PaginatedSelectMenu.tsx
  1:8  warning  'filterObject' is defined but never used  @typescript-eslint/no-unused-vars
  3:8  warning  'StylesConfig' is defined but never used  @typescript-eslint/no-unused-vars
  4:8  warning  'AnycPaginate' is defined but never used  @typescript-eslint/no-unused-vars

/home/markus/Projekte/PermaplanT/frontend/src/features/seeds/routes/SeedDetails.tsx
  36:6  warning  React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/home/markus/Projekte/PermaplanT/frontend/tailwind.config.js
  2:24  error  Require statement not part of import statement  @typescript-eslint/no-var-requires

✖ 5 problems (1 error, 4 warnings)


/home/markus/Projekte/PermaplanT/frontend/src/features/seeds/api/searchPlants.ts
  1:27  warning  'PlantsSummaryDto' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

ESLint found too many warnings (maximum: 0).

backend format...........................................................Passed
```

### LINKED ISSUE #725: build badge link broken
### Describe the Bug

_No response_

### Steps to Reproduce the Problem

visit https://github.com/ElektraInitiative/PermaplanT

### Expected Result

badge with build status

### Actual Result

broken link

### PermaplanT version

master

### Operating System

any

### Browser

any

### Versions of other relevant software/extensions

_No response_

### Additional info/logs

_No response_

### PR DESCRIPTION
**Pull request by 4ydan**
Closes #725
Closes #261 but doesnt fix new sqlfluff errors.

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by 4ydan** [comment]
@Bushuo 
Any idea how to fix this maybe? I remember I had it once but cant reproduce it locally anymore.
The hint they give doesnt seem to work in the pipeline.
image

**Comment by Bushuo** [comment]
> @Bushuo 
> 
> Any idea how to fix this maybe? I remember I had it once but cant reproduce it locally anymore.
>
> The hint they give doesnt seem to work in the pipeline.

Does the pipeline install dev dependencies at this point?
Otherwise I have no clue, sorry.

**Comment by 4ydan** [comment]
> Does the pipeline install dev dependencies at this point?
I think I just figured out. I had to install it locally. Installing it inside the docker image didnt seem to work, even though it was -g.
Now I need to add react. Thanks anyways.

**Comment by 4ydan** [comment]
Ok so this runs now the following hooks

| Hook              | Description                                                    |
|----------------------|----------------------------------------------------------------|
| check-merge-conflict | +                            |
| end-of-file-fixer    |+                          |
| mixed-line-ending    | +                    |
| trailing-whitespace  | +   |
| prettier doc            | +                        |
| prettier frontend           | +           |
| eslint              | -                |
| fmt                  | -             |
| sqlfluff-fix        | -                    |
| fix-npm-groovy-lint | +                |

eslint and fmt are already in other stages.
sqlfluff throws too many errors/warnings. I cant fix this in reasonable time.
I think this is the best compromise for now. Ready to merge.

**Comment by 4ydan** [comment]
@Bushuo 
image
I cant fix these blankspaces, they get regenerated and throw errors in the tests when I remove the blank line. Is that blank line needed? If so I would need to ignore these files somehow with pre-commit.

**Comment by Bushuo** [comment]
> @Bushuo 
> I cant fix these blankspaces, they get regenerated and throw errors in the tests when I remove the blank line. Is that blank line needed? If so I would need to ignore these files somehow with pre-commit.

Purpose of these files is Snapshot testing. If you changed the component you need to update the snapshots via `npm run test -- -u`.
There should be a message about that in the output of the test runner.

**Comment by 4ydan** [comment]
I did `npm test -- -u` and it put back the blank line. I tried changing the snapshots but it still puts back the line.

**Comment by markus2330** [comment]
Thank you, great job! :heart:

**Pull request merged**
