### PR TITLE
Fix repeated error toasts

### PR DESCRIPTION
**Pull request by badnames**
## Basics

- [x] I added a line to [changelog.md](/doc/changelog.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
Great job, beautiful and robust solution. We should add guidelines that only these functions are used (and not directly toasts anymore). And I still think we can remove all `autoClose: false`?

@absurd-turtle is it okay that we remove the webdav debug page?

Maybe we can even take this in for the release?

**Comment by markus2330** [comment]
@4ydan can you test this maybe? Would be a nice to have for the release.

**Review by 4ydan — APPROVED** [review]
Thank you for providing the `/debug` endpoint, it was very nice to test. It looked good to me, I just have one question. What happens if an error occurs and a different one during the time the alert is shown? Is the information for the user lost then (for the second error)?

**Comment by 4ydan** [comment]
@markus2330 
> Would be a nice to have for the release.

Yes, lets merge this soon.

**Comment by badnames** [comment]
> Thank you for providing the `/debug` endpoint, it was very nice to test. It looked good to me, I just have one question. What happens if an error occurs and a different one during the time the alert is shown? Is the information for the user lost then (for the second error)?

No. We keep track of all displayed toast messages using a Set data structure.
This means that there are never multiple toasts with the same message on screen.
Multiple toasts of the same type (error, info, etc.) with unique error messages can still be shown

**Pull request merged**
