### PR TITLE
CI: Checks for Frontend

### PR DESCRIPTION
**Pull request by lukashartl**
## Basics

- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by lukashartl** [comment]
@Benjaminimal
I've added support for the npm checks inside the pipeline, which you added in #171 and commented in #126. Could you please lend me a hand in fixing those js/ts problems? 🥺

**Comment by Benjaminimal** [comment]
I fixed the formatting and looked at the lining errors.
However, I'm not experienced with react and typescript so I'm not sure if I'd break anything by fixing these.
Could the authors of these files please fix them?
@absurd-turtle @buenaflor 
```
npm run lint

> permaplant@0.0.0 lint
> eslint --max-warnings=0 .

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .

frontend/src/config/index.ts
  15:22  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins

frontend/src/features/landing_page/components/GeoMap.tsx
  2:50  warning  'useMap' is defined but never used  @typescript-eslint/no-unused-vars

frontend/src/features/seeds/routes/SeedDetails.tsx
  36:6  warning  React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

frontend/src/tailwind.config.js
    1:7   warning  'colors' is assigned a value but never used     @typescript-eslint/no-unused-vars
    1:16  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
    1:16  error    'require' is not defined                        no-undef
   55:7   warning  'brown' is assigned a value but never used      @typescript-eslint/no-unused-vars
  103:7   warning  'blue' is assigned a value but never used       @typescript-eslint/no-unused-vars
  140:1   error    'module' is not defined                         no-undef

frontend/tailwind.config.js
  2:24  error  Require statement not part of import statement  @typescript-eslint/no-var-requires

✖ 10 problems (5 errors, 5 warnings)
```

**Comment by markus2330** [comment]
As this involves reformatting, we should merge this after the big release-critical PRs.

So probably release pipeline should be done first, as this will be definitely needed for the release.

**Comment by Benjaminimal** [comment]
Since I did the reformat in another PR
https://github.com/ElektraInitiative/PermaplanT/pull/160
you can drop these two commits and rebase after it is merged.
https://github.com/ElektraInitiative/PermaplanT/pull/197/commits/00a78615aabcc94a8811d73b7c0a592342e70851
https://github.com/ElektraInitiative/PermaplanT/pull/197/commits/9ab1aaf5382662a7dc9e1eb8c22caa86e9f5ab40

**Comment by lukashartl** [comment]
@badnames @absurd-turtle @markus2330 
Now that #260 ( #212 ) was merged, I fixed the rest, added the auto-generated definitions.ts to the prettier ignore-file and pushed everything to this branch. Pls review, so we can get this shipped :rocket:

**Review by markus2330 — APPROVED** [review]

**Comment by markus2330** [comment]
I wonder why there is no reformatting of Markdown. Was this forgotten as it is neither frontend nor backend?

@Benjaminimal can you plz check if all the checks of the pre-commit are done in the CI as well and create an issue of what is missing?

**Comment by markus2330** [comment]
@lukashartl great job! :heart: 

@Benjaminimal I created #261 to discuss how we fix the rest. :rocket:

**Pull request merged**
