### PR TITLE
ci: docker-compose setup (abandoned for now)

### PR DESCRIPTION
**Pull request by lukashartl**
Partially implements #37

### CODE REVIEW

**Comment by kitzbergerg** [comment]
I just ran `docker-compose up --build` and it built an ran. 

There are however a few issues for me:
* I was unable to access the App via the browser from the host. I changed the frontend entry point from `npm run dev` to `npm run dev -- --host` and then I was able to load the app from the host as well.
* I was also unable to access the backend since the port is not exposed, but adding
  ```
      ports:
        - 8080:8080
  ```
  in `docker-compose.yaml` doesn't seem to help. The backend can connect to the database, but I cannot call the backend from outside the docker-compose network which is necessary when opening the frontend in the browser.

Apart from that it might be a good idea to build the images with multiple stages. So e.g. start by building the rust binary and then use `alpine` (or another really small image) to run the executable. That way images are smaller and it might build faster. It would also be easier to split into a "build" and a "runnable" image later on if necessary (again the benefit would be that the images are way smaller as we don't need all the build dependencies).

**Comment by lukashartl** [comment]
According to #37 we are focussing on #59 (which triggered #57) right now.

@kitzbergerg thank you for your feedback

**Comment by kitzbergerg** [comment]
One more thing to note.

Since we are currently only in developing stages it is fine to build the rust image/binary with debug profile.  
But as soon as it is somewhat production ready/actually used somewhere we should build using release profile (`cargo build --release` instead of `cargo build` and the same goes for `cargo run --release`).

It probably not important right now, but we should be able to easily swap out those commands in the pipeline later on.

**Comment by Benjaminimal** [comment]
Looks good but there is one thing that I would do differently.
I like to use `docker compose` for developing locally especially for running the db.
I work from the root dir of the project so anytime I would want to start or stop a service or execute a command in a container I'd have to `cd` into the `ci` dir or add `-f ci/docker-compose.yaml` to the command.
In the projects, I have been working with we usually put the `docker-compose.yaml` in the root dir with the `Dockerfiles` and entrypoint scripts in the respective subdirectories.
Here is an example of the layout I'm proposing.
```
├── backend
│   ├── ...
│   ├── Dockerfile
│   └── entrypoint.sh
├── frontend
│   ├── ...
│   ├── Dockerfile
│   └── entrypoint.sh
├── ...
├── docker-compose.yaml
└── Jenkinsfile
```
You would have to adjust some things in the existing files as well if you take this path.
Adjust `COPY` in the `Dockerfile`s, `context` in `docker-compose.yml`, extend `.dockerignore` not to include the `Dockerfile`, ...

**Comment by markus2330** [comment]
> └── Jenkinsfile

I don't think we should put Jenkinsfile to top-level. (Btw. I generally don't like top-level files but this one docker-compose.yaml is ok.) 

But the other idea sounds like a good suggestion! Docker is only for dev, so it should be designed to be as useful as possible for dev.

@Benjaminimal do you want to take this PR over? There are also others who want to use it, so it would be good if we can get it merged while Lukas could continue to stay focused on the CI.

**Comment by Benjaminimal** [comment]
@markus2330 
Sure I can take over but I'll wait for write access on this repo.
Doing this via my fork with an existing PR and branch in here will get messy as it would need a new PR.

**Comment by markus2330** [comment]
You were just invited for write access and can push directly here.

**Comment by Benjaminimal** [comment]
Closing this for now.
If I find time for a docker development setup I'll open a new PR.

**Pull request closed without merging**
