### PR TITLE
CI: Cancel previous builds

### PR DESCRIPTION
**Pull request by 4ydan**
This will cancel a previous job on the same branch if a new one is started. #544
Should free up some computing power.

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by 4ydan** [comment]
Ok so the skipping works now, the issue is, how to handle the missing stashes when deploying PR.

**Comment by markus2330** [comment]
> The skipping works, the problem now is, how should we deal with the missing stashes in stage PR deploy.

What are the options? If a job was canceled, it also shouldn't be deployed.

**Comment by 4ydan** [comment]
Lets say you just want to change something in the mdbook and also have a new deploy. Or you change something in the frontend and you dont want to rebuild the backend, because its still the same. So we need a way to reuse already build backends. Maybe this is the place for the container registry.
With a container registry, we could always refer to the :latest from master and use that for deployment.

**Comment by markus2330** [comment]
Yes, you need a way to compare with the latest version that was actually built.

**Comment by 4ydan** [comment]
Lets do the skip stage in a separate PR, so we can get the cancel previous build going for development.

**Comment by 4ydan** [comment]
As we can [see](https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/PR-557/17/pipeline), this works and is ready to be merged 🐱

**Comment by markus2330** [comment]
Yeah, great that you also updated docu! :heart:

**Pull request merged**
