### PR TITLE
Frontend restructuring

### PR DESCRIPTION
**Pull request by badnames**
## Basics

- [x] I added a line to [changelog.md](/doc/changelog.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

### CODE REVIEW

**Comment by markus2330** [comment]
Thank you for the restructuring.

Unfortunately, there are now plenty of
```
Assets in public cannot be imported from JavaScript.
Instead of /public/permaplant-logo-gray.svg, put the file in the src directory, and use /src/permaplant-logo-gray.svg instead.
```
warnings, which we already knew about in https://github.com/ElektraInitiative/PermaplanT/issues/355#issuecomment-1717668315
Would have probably been wise to first find a solution before moving them.

**Comment by badnames** [comment]
> Thank you for the restructuring.
> 
> Unfortunately, there are now plenty of
> 
> ```
> Assets in public cannot be imported from JavaScript.
> Instead of /public/permaplant-logo-gray.svg, put the file in the src directory, and use /src/permaplant-logo-gray.svg instead.
> ```
> 
> warnings, which we already knew about in [#355 (comment)](https://github.com/ElektraInitiative/PermaplanT/issues/355#issuecomment-1717668315) Would have probably been wise to first find a solution before moving them.

Answered in the issue.

**Comment by badnames** [comment]
@markus2330 I have moved all svgs that are imported in the code to their own file in the 'src' directory.
Now, there are no more browser or build warnings as far as I can see.

**Review by 4ydan — APPROVED** [review]

**Comment by markus2330** [comment]
```
> prettier --check .


Checking formatting...

[warn] src/features/map_planning/layers/plant/PlantsLayer.tsx

[warn] Code style issues found in the above file. Forgot to run Prettier?

```

**Pull request merged**
