### PR TITLE
Polyculture use case: suggest alternatives 

### PR DESCRIPTION
**Pull request by Benjaminimal**
As requested in https://github.com/ElektraInitiative/PermaplanT/pull/120 this is the use case for suggesting plants of high ecological value.
@markus2330 
Are there any more polyculture use cases I should work on?

## Basics

- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
Excellently written! Very good insight from the meeting!

**Comment by markus2330** [comment]
> Are there any more polyculture use cases I should work on?

We added them in #1.

**Review by ThorbenStaufer — APPROVED** [review]

**Comment by Benjaminimal** [comment]
@markus2330 
I have two approvals here, can I just merge this myself, or should we always wait for you to merge it?

**Comment by markus2330** [comment]
We will discuss this in the next meeting. In short: own PRs should not be merged by yourself, others are okay if you are sure it is okay and it solves a problem for you (e.g. fixes builds).

**Pull request merged**
