### PR TITLE
installed tailwindcss eslint plugin

### PR DESCRIPTION
**Pull request by absurd-turtle**
## Basics

- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

### CODE REVIEW

**Comment by absurd-turtle** [comment]
I installed the tailwindcss eslint plugin.
It looks pretty useful to me as it suggests migrations from v2 to v3 and inconsistencies.
It found 68 problems on master.

**Comment by absurd-turtle** [comment]
```

/home/samuel/Projects/PermaplanT/frontend/src/components/Form/MarkdownEditor.tsx
  38:9  warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/components/Form/SearchInput.tsx
  94:11  warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/components/Form/SimpleFormInput.tsx
  53:9  warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/components/Form/SimpleFormTextArea.tsx
  52:9  warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/components/Layout/FullPageNav.tsx
  62:12  warning  Classnames 'pl-4, pr-4' could be replaced by the 'px-4' shorthand!  tailwindcss/enforces-shorthand

/home/samuel/Projects/PermaplanT/frontend/src/components/Layout/Navbar.tsx
  58:14  warning  Classnames 'pl-4, pr-4' could be replaced by the 'px-4' shorthand!  tailwindcss/enforces-shorthand

/home/samuel/Projects/PermaplanT/frontend/src/components/Modals/ExtendedModal.tsx
  45:16  warning  Classname 'space-between' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/components/Modals/SimpleModal.tsx
  46:14  warning  Classname 'mb' is not a Tailwind CSS class!             tailwindcss/no-custom-classname
  47:16  warning  Classname 'space-between' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/dark_mode/components/DarkModeSwitcher.tsx
  12:7  warning  Classname 'flex-shrink-0' should be updated to 'shrink-0' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/features/imprint_page/routes/ImprintPage.tsx
  11:11  warning  Classname 'title-font' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
  31:12  warning  Classname 'title-font' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
  31:12  warning  Classname 'text-1xl' is not a Tailwind CSS class!    tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/BlogOverview.tsx
   7:14  warning  Classname 'body-font' is not a Tailwind CSS class!                             tailwindcss/no-custom-classname
  12:19  warning  Classnames 'mb-4, mt-4' could be replaced by the 'my-4' shorthand!             tailwindcss/enforces-shorthand
  12:19  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname
  26:19  warning  Classname 'flex-shrink-0' should be updated to 'shrink-0' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  28:23  warning  Classname 'flex-grow' should be updated to 'grow' in Tailwind CSS v3!          tailwindcss/migration-from-tailwind-2
  29:25  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/CTA.tsx
   5:14  warning  Classname 'body-font' is not a Tailwind CSS class!   tailwindcss/no-custom-classname
   8:15  warning  Classname 'title-font' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
  17:15  warning  Classname 'title-font' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/Contact.tsx
  10:14  warning  Classname 'body-font' is not a Tailwind CSS class!                             tailwindcss/no-custom-classname
  13:15  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname
  28:19  warning  Classname 'bg-opacity-50' should be replaced by an opacity suffix (eg. '/50')  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/Features.tsx
  37:15  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname
  73:20  warning  Classname 'flex-shrink-0' should be updated to 'shrink-0' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  76:20  warning  Classname 'flex-grow' should be updated to 'grow' in Tailwind CSS v3!          tailwindcss/migration-from-tailwind-2
  77:21  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/Pricing.tsx
  21:14  warning  Classname 'body-font' is not a Tailwind CSS class!                                   tailwindcss/no-custom-classname
  24:15  warning  Classname 'title-font' is not a Tailwind CSS class!                                  tailwindcss/no-custom-classname
  30:18  warning  Classname 'whitespace-no-wrap' is not a Tailwind CSS class!                          tailwindcss/no-custom-classname
  33:21  warning  Classnames 'rounded-bl, rounded-tl' could be replaced by the 'rounded-l' shorthand!  tailwindcss/enforces-shorthand
  33:21  warning  Classname 'title-font' is not a Tailwind CSS class!                                  tailwindcss/no-custom-classname
  36:21  warning  Classname 'title-font' is not a Tailwind CSS class!                                  tailwindcss/no-custom-classname
  39:21  warning  Classname 'title-font' is not a Tailwind CSS class!                                  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/Team.tsx
   7:14  warning  Classname 'body-font' is not a Tailwind CSS class!   tailwindcss/no-custom-classname
  10:15  warning  Classname 'title-font' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/Teammember.tsx
  11:11  warning  Classname 'flex-shrink-0' should be updated to 'shrink-0' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  13:14  warning  Classname 'flex-grow' should be updated to 'grow' in Tailwind CSS v3!          tailwindcss/migration-from-tailwind-2
  14:15  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/landing_page/components/Testimonials.tsx
   4:16  warning  Classname 'body-font' is not a Tailwind CSS class!                             tailwindcss/no-custom-classname
   6:15  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname
  27:21  warning  Classname 'flex-shrink-0' should be updated to 'shrink-0' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  29:25  warning  Classname 'flex-grow' should be updated to 'grow' in Tailwind CSS v3!          tailwindcss/migration-from-tailwind-2
  30:27  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname
  57:21  warning  Classname 'flex-shrink-0' should be updated to 'shrink-0' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  59:25  warning  Classname 'flex-grow' should be updated to 'grow' in Tailwind CSS v3!          tailwindcss/migration-from-tailwind-2
  60:27  warning  Classname 'title-font' is not a Tailwind CSS class!                            tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/map_planning/components/toolbar/LayerList.tsx
  55:14  warning  Classname 'grid-cols' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/map_planning/components/toolbar/LayerListItem.tsx
  74:13  warning  Classname 'flex-shrink' should be updated to 'shrink' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/features/map_planning/components/toolbar/Toolbar.tsx
   7:8   warning  Classnames 'pb-2, pt-2' could be replaced by the 'py-2' shorthand!         tailwindcss/enforces-shorthand
   7:8   warning  Classname 'horizontal-handle' is not a Tailwind CSS class!                 tailwindcss/no-custom-classname
  15:8   warning  Classname 'vertical-handle' is not a Tailwind CSS class!                   tailwindcss/no-custom-classname
  88:17  warning  Classname 'flex-shrink' should be updated to 'shrink' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2

/home/samuel/Projects/PermaplanT/frontend/src/features/map_planning/layers/base/components/DistanceMeasurementModal.tsx
  53:12  warning  Classname 'w-ful' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/map_planning/layers/plant/components/EmptyList/EmptyAvailablePlants.tsx
  9:13  warning  Classname 'text-md' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/map_planning/layers/plant/components/PlantSuggestionList.stories.tsx
  9:12  warning  Classname 'w-100' is not a Tailwind CSS class!  tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/maps/routes/MapCreateForm.tsx
   83:11  warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
   96:11  warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  164:9   warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  191:9   warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  197:12  warning  Classname 'space-between' is not a Tailwind CSS class!                                                       tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/maps/routes/MapEditForm.tsx
  218:15  warning  Classname 'placeholder-neutral-500' should be updated to 'placeholder:text-neutral-500' in Tailwind CSS v3!  tailwindcss/migration-from-tailwind-2
  224:18  warning  Classname 'space-between' is not a Tailwind CSS class!                                                       tailwindcss/no-custom-classname

/home/samuel/Projects/PermaplanT/frontend/src/features/seeds/components/SeedsOverviewList.tsx
   97:21  warning  Classname 'bg-primary-textfield' is not a Tailwind CSS class!       tailwindcss/no-custom-classname
   97:21  warning  Classname 'dark:hover-bg-neutral-600' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
  112:25  warning  Classnames 'px-6, py-6' could be replaced by the 'p-6' shorthand!   tailwindcss/enforces-shorthand

✖ 68 problems (0 errors, 68 warnings)
  0 errors and 28 warnings potentially fixable with the `--fix` option.
```

**Comment by markus2330** [comment]
@absurd-turtle thx for checking! What about the `--fix` option, can it really fix 28 warnings? Are the others difficult to fix?

**Comment by absurd-turtle** [comment]
> @absurd-turtle thx for checking! What about the `--fix` option, can it really fix 28 warnings? Are the others difficult to fix?

I executed the automatic fix and it indeed fixed 28 of the warnings.
I think it was mostly migrations to the new tailwindcss version e.g.
"13:14  warning  Classname 'flex-grow' should be updated to 'grow' in Tailwind CSS v3!          tailwindcss/migration-from-tailwind-2"

I pushed the changes it did to this PR.

**Pull request closed without merging**
