### PR TITLE
fixes #187

### LINKED ISSUE #187: Unexpected darkMode toggle
## Steps to Reproduce the Problem

Reload current page.

## Expected Result

The website should not change the darkMode.

## Actual Result

The darkMode setting gets toggled.

## System Information

- PermaplanT: master

### PR DESCRIPTION
**Pull request by absurd-turtle**
## Basics

- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [x] I fixed all affected decisions
- [x] I added code comments, logging, and assertions as appropriate
- [x] I mentioned [every code](/.reuse/dep5) not directly written by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
https://pr.permaplant.net still toggles?

**Comment by markus2330** [comment]
@buenaflor can you check if this fixes the problem?

**Comment by absurd-turtle** [comment]
jenkins build please

**Comment by absurd-turtle** [comment]
> https://pr.permaplant.net still toggles?

I have tried it again. After I clear the website caches it works fine :)

**Review by markus2330 — APPROVED** [review]

**Pull request merged**
