### PR TITLE
Documentation/architecture

### PR DESCRIPTION
**Pull request by markus2330**
## Basics

- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by Bushuo** [comment]
@markus2330 I added the things we discussed today to the solution strategy page of the docs.
Please take a look if anything is missing or needs to be elaborated on.

**Comment by Bushuo** [comment]
> @Bushuo excellent job&great help, you found the exact right place for that! I'll extend tomorrow. If you have a bit more time, you could write more about the protocol of the websocket, can this somehow be shared with what undo/redo uses?
>
@markus2330 I am working on a prototypical implementation for it.
I decided to use sse instead of websockets though. I think we do not need the duplex connection, just the ability to push to clients.
I guess it can be somehow shared but I did not try it in my implementation yet.  
> Also for how layers work across years is a topic some words should be written there.
> 
I will add that tomorrow. I think the state can be a map from years -> objects existing within those years

> Btw. are there updates needed for map_lazyloading.md map_undo_redo_implementation.md frontend_state_management.md frontend_state_offloading.md?
>
I think so. But I first want to get a prototype working that works for add, delete and movement of a square.

**Comment by markus2330** [comment]
> I am working on a prototypical implementation for it.

As we will use it (if it works) you can consider it as tracer bullet.

> I decided to use sse instead of websockets though. I think we do not need the duplex connection, just the ability to push to clients.

Yes, absolutely, you are right, I fixed it in the documentation.

Actix seems to support SSE quite well, e.g. https://github.com/arve0/actix-sse/

> I guess it can be somehow shared but I did not try it in my implementation yet.

I already reworked the 4 decisions. I also changed the decisions about offloading.

What is still left is how we structure the state more efficiently (elements of different layers in different years).

**Comment by markus2330** [comment]
@Bushuo Last updates for now, you can push changes. There is a todo for you in 04solution.md

Looking forward to your tracer bullet, I cross the fingers everything works :crossed_fingers:

**Pull request merged**
