### PR TITLE
pre-commit: add hook for sql files

### PR DESCRIPTION
**Pull request by Benjaminimal**
I configured a pre-commit hook for auto-fixing formatting and linting errors in SQL files.
It uses [sqlfluff](https://sqlfluff.com/).
This enforces our [database guidelines](https://github.com/ElektraInitiative/PermaplanT/issues/155).

## Basics

- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
Thank you for maintaining the pre-commits, great job!

**Review by aidnurs — COMMENTED** [review]
I agree in general that there should a common formatting for every piece in the project. However, I would like to share my personal experience using precommit and sqlfluff. 

Personally, I would avoid formatting or any code manipulation during the precommit hook, since the developer is not aware of what code gets committed after all. I also remember there are some sqlfluff rules(when not considered) that could break the whole production environment.

I'm not really against the change, just wanted to share my personal experience here

**Comment by Benjaminimal** [comment]
The code wouldn't get committed right away.
If sqlfluff finds something it will fix what it can and will do a non-zero exit.
This makes pre-commit abort the commit, the developer can look at the changes before committing them again.

Can you remember what rules were problematic?

**Comment by absurd-turtle** [comment]
@markus2330 Should we merge this?

**Comment by markus2330** [comment]
@absurd-turtle Would be great but ideally first we do:

1. #206
2. reformat all the SQL files, so that #261 doesn't get even bigger

Do you want to work on that?

**Comment by absurd-turtle** [comment]
> @absurd-turtle Would be great but ideally first we do:
> 
>     1. [Squash existing migrations. #206](https://github.com/ElektraInitiative/PermaplanT/issues/206)
> 
>     2. reformat all the SQL files, so that [pre-commit run --all-files fails #261](https://github.com/ElektraInitiative/PermaplanT/issues/261) doesn't get even bigger
> 
Ah ok, I just wondered why this isn't merged yet.

> Do you want to work on that?
No, not really. I want to focus on the Nextcloud integration tasks next.

**Comment by markus2330** [comment]
> I want to focus

I also don't think it is something we should focus right now. Let us get the basic use cases done and this can be fixed during bug fixing phase.

**Comment by markus2330** [comment]
@absurd-turtle as you already looked at it, is there a specific reason why you didn't give your approval?

**Comment by absurd-turtle** [comment]
> @absurd-turtle as you already looked at it, is there a specific reason why you didn't give your approval?

Nope

**Review by absurd-turtle — APPROVED** [review]

**Comment by markus2330** [comment]
jenkins build please

**Comment by badnames** [comment]
@markus2330 Another stale PR, what are we going to do about it?

**Comment by markus2330** [comment]
Here we wait on purpose until we squash migration commits.

**Comment by temmey** [comment]
i cherry picked the commit into #644, this pr can be closed

**Pull request closed without merging**
