### PR TITLE
Base layer right toolbar: fix wrong value being assigned to scale input.

### PR DESCRIPTION
**Pull request by badnames**
## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
Great to have this, let us see what the build server says.

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
@4ydan Do you know why it timed out? https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/fix%2F713-base-map-not-shown-after-selecting/3/pipeline (it is the irrelevant branch PR anyway, so I will merge).

**Comment by 4ydan** [comment]
Yes, the video shows that the map is already created that the test wants to create.

**Comment by 4ydan** [comment]
I also saw one where the backend wasnt reachable yet, need to add a wait.

**Comment by 4ydan** [comment]
Having a delete function would help a lot since I could reset the state myself after a test. Right now I am not sure how a map with the name `SUTPublicMap` is already created when the test that should create it fails.

**Comment by 4ydan** [comment]
Maybe it was a race condition between the PR process and the Branch process and the lock just didnt work.

**Comment by markus2330** [comment]
One more reason to get rid of the branch process :wink: #587

**Comment by 4ydan** [comment]
Hm ok it seems like the lock worked.
image

**Pull request merged**
