### PR TITLE
Database: Squash Migrations

### PR DESCRIPTION
**Pull request by Benjaminimal**
Squashed existing backend migrations in so that we can see the database schema more clearly.
To ensure that the schemata are still the same I generated a schema-only dump before and after applying these new migrations with this command `pg_dump --schema-only -f schema.sql --dbname permaplant` and compared the resulting files with `diff`.
As you can see the only differences are the naming of constraints and sequences which is not surprising since the table names changed.
```
diff old_schema.sql new_schema.sql 
350,352c350,352
<     CONSTRAINT plant_detail_hardiness_zone_check CHECK (((hardiness_zone IS NULL) OR ((hardiness_zone >= 0) AND (hardiness_zone <= 13)))),
<     CONSTRAINT plant_detail_heat_zone_check CHECK (((heat_zone IS NULL) OR ((heat_zone >= 0) AND (heat_zone <= 13)))),
<     CONSTRAINT plant_detail_preferable_permaculture_zone_check CHECK (((preferable_permaculture_zone IS NULL) OR ((preferable_permaculture_zone >= '-1'::integer) AND (preferable_permaculture_zone <= 6))))
---
>     CONSTRAINT plants_hardiness_zone_check CHECK (((hardiness_zone IS NULL) OR ((hardiness_zone >= 0) AND (hardiness_zone <= 13)))),
>     CONSTRAINT plants_heat_zone_check CHECK (((heat_zone IS NULL) OR ((heat_zone >= 0) AND (heat_zone <= 13)))),
>     CONSTRAINT plants_preferable_permaculture_zone_check CHECK (((preferable_permaculture_zone IS NULL) OR ((preferable_permaculture_zone >= '-1'::integer) AND (preferable_permaculture_zone <= 6))))
359c359
< -- Name: plant_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: permaplant
---
> -- Name: plants_id_seq; Type: SEQUENCE; Schema: public; Owner: permaplant
362c362
< CREATE SEQUENCE public.plant_detail_id_seq
---
> CREATE SEQUENCE public.plants_id_seq
371c371
< ALTER TABLE public.plant_detail_id_seq OWNER TO permaplant;
---
> ALTER TABLE public.plants_id_seq OWNER TO permaplant;
374c374
< -- Name: plant_detail_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: permaplant
---
> -- Name: plants_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: permaplant
377c377
< ALTER SEQUENCE public.plant_detail_id_seq OWNED BY public.plants.id;
---
> ALTER SEQUENCE public.plants_id_seq OWNED BY public.plants.id;
430c430
< ALTER TABLE ONLY public.plants ALTER COLUMN id SET DEFAULT nextval('public.plant_detail_id_seq'::regclass);
---
> ALTER TABLE ONLY public.plants ALTER COLUMN id SET DEFAULT nextval('public.plants_id_seq'::regclass);
449c449
< -- Name: plants plant_detail_binomial_name_key; Type: CONSTRAINT; Schema: public; Owner: permaplant
---
> -- Name: plants plants_binomial_name_key; Type: CONSTRAINT; Schema: public; Owner: permaplant
453c453
<     ADD CONSTRAINT plant_detail_binomial_name_key UNIQUE (binomial_name);
---
>     ADD CONSTRAINT plants_binomial_name_key UNIQUE (binomial_name);
457c457
< -- Name: plants plant_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: permaplant
---
> -- Name: plants plants_pkey; Type: CONSTRAINT; Schema: public; Owner: permaplant
461c461
<     ADD CONSTRAINT plant_detail_pkey PRIMARY KEY (id);
---
>     ADD CONSTRAINT plants_pkey PRIMARY KEY (id);
```

@NurramoX 
Can you please verify that the style in the new migration files adheres to what you wrote here?
https://github.com/ElektraInitiative/PermaplanT/pull/175
I let [sqlfluff](https://sqlfluff.com/) run over it which I want to add as a pre-commit hook.

## Basics

- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by Benjaminimal** [comment]
@lukashartl 
I'm not sure how to apply this to https://dev.permaplant.net/.
All that is needed is `diesel database reset` but this would of course wipe all data.

For https://pr.permaplant.net/ this shouldn't be an issue since the database gets wiped anyway on deployment, right?

**Comment by markus2330** [comment]
> For https://pr.permaplant.net/ this shouldn't be an issue since the database gets wiped anyway on deployment, right?

Yes, as you also see by the successful build.

For dev.permaplant.net we can wipe the database manually after we merged this.

**Review by markus2330 — APPROVED** [review]
Thank you, great job.

**Review by badnames — APPROVED** [review]

**Comment by markus2330** [comment]
As discussed, we will do this after @aidnurs finished the plants DB.

**Review by aidnurs — APPROVED** [review]
Looks great! 
Regarding the reset of the database on other environments:
I suppose squashing the migrations will be our regular practice, there should be some functionality in Diesel to squash them without losing the data. For example, there are baseline migrations in Flyway https://flywaydb.org/documentation/concepts/baselinemigrations
Hopefully, this will help you

**Comment by Benjaminimal** [comment]
Closing it since it has to be redone when the plants table is stable.

**Pull request closed without merging**
