### PR TITLE
CI: Login/Logout e2e test

### PR DESCRIPTION
**Pull request by 4ydan**
Login Logout feature test according to the testing strategy.

- Readme still work in progress, will be extended slowly.
- login_logout.feature
- Saves a video as artifact (~200kb).

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by 4ydan** [comment]
The agent with the label `permaplant && pr` does not have docker installed.

**Comment by 4ydan** [comment]
Following problem, we said we want to perform the e2e tests inside the PR stage, so PR is locked. But the PR stage nodes don't have docker installed, so I cant run the tests their either.

**Comment by markus2330** [comment]
I am not sure if I understand what you want to say (what is PR stage? what is a locked PR?) but anyway: my idea was that the e2e tests are executed **after** the deployment (extra stage) on a node with docker (connecting to pr.permaplant.net). Don't hesitate to ask and/or explain me what locked/PR/stage is?

**Comment by 4ydan** [comment]
Well my fear was that when I perform the tests on pr.permaplant.net, that someone elses PR overwrites the deployment on pr.permaplant.net and my tests fail or test something different.

Then I found out that there is only one node deploying pr.permaplant and that I could do the tests inside that node, but that exactly is the issue from above. When I do the tests in another node, the pr.permaplant node is free and can deploy something new.

Locked PR -> the node pr.permaplant on Jenkins is in use.
PR stage -> The jenkins stage "Deploy PR", which comes after the parallel stage and is the last stage in CI for pull requests.

**Comment by markus2330** [comment]
I think your worries are easily fixable via https://plugins.jenkins.io/lockable-resources/

**Comment by 4ydan** [comment]
Ready to be merged, map e2e tests shortly after this merge.

**Comment by markus2330** [comment]
Looks great! :heart:

**Pull request merged**
