### PR TITLE
backend testing strategy

### PR DESCRIPTION
**Pull request by kitzbergerg**
## Basics

- [ ] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [ ] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by kitzbergerg** [comment]
I would make actual implementation changes in a separate PR.

**Review by Benjaminimal — APPROVED** [review]

**Review by Bushuo — APPROVED** [review]

**Review by badnames — APPROVED** [review]

**Comment by kitzbergerg** [comment]
@markus2330 Since we don't actually use 'integration tests' according to our current definition I think we should redefine those.

I would propose to call integration tests all tests we put in the `src/test/` directory which are supposed to test multiple layers (therefore the test we currently have would be called integration tests from now on). 
Unit tests on the other hand should be put directly in the files where their related functions are and they are only supposed to test individual modules/functions (we currently wouldn't have any unit tests, but we might in the future).

**Comment by markus2330** [comment]
> Since we don't actually use 'integration tests' according to our current definition (and probably never will) I think we should redefine those.

Yes.

> I would propose to call integration tests all tests we put in the src/test/ directory which are supposed to test multiple layers (therefore the test we currently have would be called integration tests from now on).
Unit tests on the other hand should be put directly in the files where their related functions are and they are only supposed to test individual modules/functions (we currently wouldn't have any unit tests, but we might in the future).

Sounds like a good idea. Probably we should call them "backend integration tests", though as there will be probably also "frontend integration tests" (testing frontend with available backend).

**Comment by markus2330** [comment]
Closing was by accident :wink:

**Comment by kitzbergerg** [comment]
@markus2330 Unless the latest commit introduced unwanted changes this can be merged. The actual implementation is part of #302. If there are other changes necessary I would add them over there.

**Pull request merged**
