### PR TITLE
testing strategy - add more integration tests 

### LINKED ISSUE #353: testing strategy - add more integration tests
Tracking issue for adding more integration tests.

Follow up to #39, #289 and #302.

### PR DESCRIPTION
**Pull request by kitzbergerg**
Add integration tests for endpoints that weren't tested (enough).

Resolves #353.

## Basics

- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Review by markus2330 — CHANGES_REQUESTED** [review]
Please click all the items in  the top-post of the PR (at least "Basics") before requesting reviews. Then you would have noticed that there was/is(?) a build server problem.

**Comment by markus2330** [comment]
jenkins build please

**Comment by kitzbergerg** [comment]
> Please click all the items in the top-post of the PR (at least "Basics") before requesting reviews. Then you would have noticed that there was/is(?) a build server problem.

This doesn't seem to be an issue in the PR itself, but rather in the build. At least the PR merge works just fine and locally everything compiles as well.
Do I have to do anything here now?

**Comment by markus2330** [comment]
Yes, in general

- you should retrigger the pipeline (several times if needed) and if this doesn't work report an issue/ask our CI guys etc. (If you cannot fix it yourself.)
- Furthermore, the points in the top post are still not ticked (a few of them should be already okay).

In this specific case it seems to be (again) the situation that the cargo fetches fail. I already discussed with @lukashartl, a solution is that we already install cargo packages when building the Docker image. But we need to tell him that it fails now, so that he can put this higher in his priority list.

**Comment by markus2330** [comment]
to be rebased after auth merge

**Comment by kitzbergerg** [comment]
@markus2330 Can be merged.

**Comment by markus2330** [comment]
There is a "please merge" label which is less noisy. (But might need a day or so until I notice it.)

**Pull request merged**
