### PR TITLE
Backend code refactoring

### PR DESCRIPTION
**Pull request by kitzbergerg**
A start to #60 and #65.

### CODE REVIEW

**Comment by kitzbergerg** [comment]
@markus2330 Is it ok to change the error response in the backend? Previously `ResponseBody` was used for errors as well. That however has no benefit at all as `data` was always empty. In this PR I change the response to be just a string. If this is a problem I'll change it back.

Generally I would prefer to not use `ResponseBody` as the `message` part of that struct is mostly unnecessary in my opinion. Currently the only thing that is sent in `message` is `ok`, but we can just use the status code to convey that the request was successful.
This would however require a change in the frontend as well so I don't know how to handle that.

**Comment by markus2330** [comment]
> Is it ok to change the error response in the backend?

Yes, totally. Looking forward to see a nice error concept by a Rust expert! :1st_place_medal: 

Can you write a small technical document on how to handle errors in PermaplanT for Rust novices?

> mostly unnecessary

When is it necessary? Is it worth to have differences in the APIs in these situations?

> This would however require a change in the frontend as well so I don't know how to handle that.

Due to typeshare+typescript it will give you compile errors.

**Comment by kitzbergerg** [comment]
> Can you write a small technical document on how to handle errors in PermaplanT for Rust novices?

I would make that part of the high level doc using `mdBook`.

> > mostly unnecessary
> 
> When is it necessary? Is it worth to have differences in the APIs in these situations?
> 
> > This would however require a change in the frontend as well so I don't know how to handle that.
> 
> Due to typeshare+typescript it will give you compile errors.

Maybe create a separate issue for that.

**Review by markus2330 — APPROVED** [review]
Thank you for the improvements!

In general we are missing code comments. Most of the devs are new to Rust, so some explanations of the code are useful.

> I would make that part of the high level doc using mdBook.

:+1: This should be the next step.

>   Maybe create a separate issue for that.

Or a separate PR so that we can see the compile error. But first we should clarify the architecture, so that we don't need to go back and forth.

**Comment by kitzbergerg** [comment]
> In general we are missing code comments. Most of the devs are new to Rust, so some explanations of the code are useful.

This will be part of #60 (which I'm already working on). Part of that forces you to write doc for every method in the project.

**Comment by markus2330** [comment]
Please don't self-merge, see also #62. But I was just waiting for your answer and would have merged then, so nothing happened.

**Comment by kitzbergerg** [comment]
Oh sorry about that then. You approved the request so I thought it would be fine.

**Pull request merged**
