### PR TITLE
Feature/1154 area of plants left overs

### PR DESCRIPTION
**Pull request by Bushuo**
## Basics

- [ ] I added a line to [changelog.md](/doc/changelog.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages and changelog.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines

### CODE REVIEW

**Comment by Bushuo** [comment]
@markus2330
Please check again if this approach would also work. I added additional info to the plant attribute form.
I also renamed `width` and `height` in the database to `size_x` and `size_y` for plantings. This makes more sense because those are the values that get used in the 2D editor, to display the shapes.
`height` can be added back later, with the correct semantics.

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
> Please check again if this approach would also work. I added additional info to the plant attribute form.

Please specify in more detail what the approach is and what the approach should solve :wink: The additional info in the plant attribute looks very nice :+1:

In particular: Please tick (and write) what was done in #1154, so that is clear what we should check for.

**Comment by Bushuo** [comment]
jenkins build please

**Comment by Bushuo** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
Fascinating, very well done! :heart: 

The relationship lines somehow do not update anymore (also not from non-field plants), even though they are all initially drawn correctly.

@yvonnemarkl will hopefully also have time to take a look.

**Comment by Bushuo** [comment]
@markus2330
What do you mean by do not update?
On my machine, they show and change their position if one of the plantings on the end of the line is moved.

**Comment by markus2330** [comment]
> What do you mean by do not update?
> On my machine, they show and change their position if one of the plantings on the end of the line is moved.

@Bushuo I created #1178 to explain what I mean. The problem was already introduced earlier (I was able to reproduce it on dev.permaplant.net before merging this PR), thus I merged this PR. Great job with this PR :rocket: :heart:

**Pull request merged**
