### PR TITLE
Plant Relations Visuals

### PR DESCRIPTION
**Pull request by Bushuo**
Ref: #435 
Implements the plant relation visuals

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by markus2330** [comment]
For me this works super-nice, I found only:

- [ ] The icons of the plant that gets planted (e.g. Tomato) flicker in the already-placed plants.
- [ ] when moving plants the lines do not follow the cursor (only when stopping moving you see the lines)

Unrelated things I noticed:

- [ ] Hover-text is still a bit overlapping with the cursor.
- [ ] it would be great if planting could be aborted with "Esc"

Feel free to make follow-up issues if they are not easy to fix.

**Comment by 4ydan** [comment]
Jenkins build please

**Comment by 4ydan** [comment]
I tried hard to make your future run, but I spent too much time with it now and just couldn't make it. I also can't really say much about your code, because I'm not really experienced with what you are doing. Maybe the 2-3 magical numbers in the tooltip could be noted better. I hope I can try out your next future.

**Comment by Bushuo** [comment]
> I tried hard to make your future run, but I spent too much time with it now and just couldn't make it. I also can't really say much about your code, because I'm not really experienced with what you are doing. Maybe the 2-3 magical numbers in the tooltip could be noted better. I hope I can try out your next future.

Don't worry. Thanks for trying it anyway :)

**Comment by 4ydan** [comment]
Thanks again for helping me to get this to work. I would have never achieved it alone, simply because I didn't know this #[600](https://github.com/ElektraInitiative/PermaplanT/issues/600) was necessary and also because of small usibility issues.

So everything works as it should. Great work.

**Review by 4ydan — APPROVED** [review]
Thanks again for helping me to get this to work. I would have never achieved it alone, simply because I didn't know this #https://github.com/ElektraInitiative/PermaplanT/issues/600 was necessary and also because of small usibility issues.

So everything works as it should. Great work.

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
Great job :heart: Yvonne also loves this feature, so well done! :rocket: 

Map date also works fine.

**Pull request merged**
