### PR TITLE
CI: Parallelizing cargo build and test

### PR DESCRIPTION
**Pull request by 4ydan**
#472 

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by markus2330** [comment]
> Goal: 20minutes
> With caching we can probably go down to 10mins per run.

Very ambitious, I like it :1st_place_medal:

**Comment by 4ydan** [comment]
image

**Comment by 4ydan** [comment]
If this is something we want, it's ready to be merged as temporal solution until we can speed up the builds in some other way. It costs one more node per Jenkins jobs though.
I also found some duplicate changelogs from me, removed them.

**Comment by 4ydan** [comment]
image
With proper parallelizing we could even reach faster times.

**Comment by markus2330** [comment]
Yes, then parallelizing build+test seems to make sense. Will it make trouble for the later caching?

Anything that speaks against merging it? You seem to be hesitant :question:

**Comment by markus2330** [comment]
Btw. a big thanks for your investigations!

**Comment by 4ydan** [comment]
I have a bigger suggestion coming, need to finish the drawing.

> Anything that speaks against merging it? You seem to be hesitant ❓

No, not really, I just got distracted by other stuff and forgot about this.

**Comment by 4ydan** [comment]
image
I hope this visualizes the ideas well.

**Review by lukashartl — APPROVED** [review]
Looks FANTASTIC! Also very nice drawings!!

**Comment by 4ydan** [comment]
https://github.com/rust-lang/cargo/issues/5656#issuecomment-583958762
Interesting thoughts from a rust-lang developer

I also just realized that cargo build is doing a cargo check, so is this redundant?

**Comment by 4ydan** [comment]
This is not increasing the speed of each individual subtask but rather increases the throughput by executing everything in parallel but having increased subtask times. With caching subtask times can be further optimized and probaly achieve runs below 5 minutes.

At first I didn't intend to change that many lines, but splitting everything up made me repeat so many lines, that I had to extract a lot.

## Some data

[Old pipeline](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-669/2/pipeline)

For simplicity I ignore the frontend and mdbook stages

| Task                   | Old pipeline (minutes) | New pipeline (minutes) |
|------------------------|--------------------|--------------------|
| frontend               | untouched          | untouched          |
| mdbook                 | untouched          | untouched          |

### [Run 81](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-577/81/pipeline/66) 4 node parallel clippy benefit from check 
| Task                | Old pipeline (minutes) | New pipeline (minutes) |
|---------------------|------------------------|------------------------|
| cargo test          | 06:25                  | 06:47                  |
| cargo build         | 07:08                  | 15:00                  |
| cargo check + clippy| 05:58 + 00:51          | 10:00                  |
| cargo doc           | 03:10                  | 08:10                  |
| **Subtask Total*    | **22:41**              | **39:57**              |
| **Pipeline Total*   | **24:58**              | **16:13**              |

#### [Run 83](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-577/83/pipeline) 3 node parallel clippy benefit from build
**This run was very inflated because of libelektra and docker image builds** but still
| Task                | Old pipeline (minutes) | New pipeline (minutes) |
|---------------------|------------------------|------------------------|
| cargo test          | 06:25                  | 11:06(i7)              |
| cargo build + clippy| 07:08 + 00:51          | 12:54(h1)              |
| cargo check + doc   | 05:58 + 03:10          | 12:35(a7)              |
| **Subtask Total*    | **22:41**              | **36:35**              |
| **Pipeline Total*   | **24:58**              | **?**                  |

### [Run 84](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-577/84/pipeline) RERUN 3 node parallel clippy benefit from build 
| Task                | Old pipeline (minutes) | New pipeline (minutes) |
|---------------------|------------------------|------------------------|
| cargo test          | 06:25                  | 08:07(a7)              |
| cargo build + clippy| 07:08 + 00:51          | 12:40(h1)              |
| cargo check + doc   | 05:58 + 03:10          | 10:42(v2)              |
| **Subtask Total*    | **22:41**              | **31:29**              |
| **Pipeline Total*   | **24:58**              | **16:10**              |

### [Run 85](https://build.libelektra.org/blue/organizations/jenkins/PermaplanT/detail/PR-577/85/pipeline) RERUN 3 node parallel clippy benefit from build

| Task                | Old pipeline (minutes) | New pipeline (minutes) |
|---------------------|------------------------|------------------------|
| cargo test          | 06:25                  | 12:29(l1)              |
| cargo build + clippy| 07:08 + 00:51          | 12:48(h1)              |
| cargo check + doc   | 05:58 + 03:10          | 10:44(v2)              |
| **Subtask Total*    | **22:41**              | **37:01**              |
| **Pipeline Total*   | **24:58**              | **17:02**              |

If we look at Run 83 and 84 `cargo check + doc` a strong node seems to speed up a subtask by 2 minutes. Moreover I think jenkins scheduler trys to give me the same nodes for the same stages. So I am not sure how comparable this is. However subtask duration is surely higher this way, but not sure by how much truely.

33% speedup by increasing the cpu time and using more nodes.

I also logged into pr.permaplant.net everything seemed to work.

I asked in rust-lang about this testing strategy, this is what they said.
image

More can be done here, but we can also merge/close now and open additional PR's.

**Pull request merged**
