### PR TITLE
ci: rename permaplant service

### PR DESCRIPTION
**Pull request by lukashartl**
## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Review by markus2330 — APPROVED** [review]
LGTM, let us see the result.

**Comment by lukashartl** [comment]
`npm run insert` fails because of a password error ... I'll investigate right away

**Comment by markus2330** [comment]
Thx!

**Comment by lukashartl** [comment]
Pipeline restarted :) Let's see 😄

**Comment by 4ydan** [comment]
All E2E tests failed, 
image

**Comment by markus2330** [comment]
successful except of E2E tests, could be a spurious error

**Comment by markus2330** [comment]
jenkins build please

**Comment by lukashartl** [comment]
I already found the problem - I accidentally executed the apache playbook with `--check` (basically no-op). Should be fixed and pipeline is running 😄

**Comment by markus2330** [comment]
@4ydan do we merge this or do you want to pick these changes and put them into #648?

**Comment by 4ydan** [comment]
Just ignore https://github.com/ElektraInitiative/PermaplanT/pull/648 for now.

**Comment by lukashartl** [comment]
Pipeline is 💚

**Comment by markus2330** [comment]
@lukashartl Great job! Good to have a simpler setup! Migration worked flawlessly! :green_heart: 

But probably #780 was introduced?

**Pull request merged**
