### PR TITLE
Fix a bug where the image error toast would show unexpectedly

### LINKED ISSUE #617: "Sorry! I couldn't load the image. ..." is always displayed.
### Describe the Bug

The toast with the image loading error is always displayed.

### Steps to Reproduce the Problem

Open the landing page.
Check the network tab, all images are loading.

### Expected Result

The message only appears if a image fails to load.

### Actual Result

The message appears anyway.

### PermaplanT version

master

### Operating System

MacOS

### Browser

Chrome Version 114.0.5735.198 (Official Build) (arm64)

### Versions of other relevant software/extensions

_No response_

### Additional info/logs

_No response_

### PR DESCRIPTION
**Pull request by ThorbenStaufer**
Error notification was falsely configured to also fire while the image requests are still loading.

Resolves #617.

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by markus2330** [comment]
@ThorbenStaufer thank you so much for the quick fix! :heart:

**Review by 4ydan — APPROVED** [review]
Great, it's gone.

**Review by Bushuo — COMMENTED** [review]
Problem with this approach is, it will fire for every image that gets loaded under this endpoint.
Another way to handle errors was introduced by @absurd-turtle in a recent PR.
But we can look at it in #505

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
> Problem with this approach is, it will fire for every image that gets loaded under this endpoint.

Do I understand correctly that this problem is not introduced in this PR?

If it doesn't introduce a new problem I would like to merge it as workaround.

> But we can look at it in https://github.com/ElektraInitiative/PermaplanT/issues/505

:+1: :heart:

**Review by markus2330 — APPROVED** [review]
LGTM

**Comment by 4ydan** [comment]
This needs #624 merged to pass checks.

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
Would love to have this as part of next release.

**Comment by Bushuo** [comment]
@markus2330 
This is currently failing due to an unrelated issue.
I think it can be merged.

**Review by Bushuo — APPROVED** [review]

**Pull request merged**
