### PR TITLE
Added cancel confirmation to Guided Tour

### LINKED ISSUE #738: allow cancel of aborting tour
### Describe the Bug

as we saw in the user study, people press on the x and want the tour back

### Steps to Reproduce the Problem

press x

### Expected Result

There should be a confirmation dialog with 3 options:

- continue tour
- restart tour next time
- disable this tour for me

### Actual Result

no possibility to continue the tour

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

### Versions of other relevant software/extensions

_No response_

### Additional info/logs

_No response_

### LINKED ISSUE #752: `ModalOverlay` of Guided Tour disappears after canceling skip
### Describe the Bug

_No response_

### Steps to Reproduce the Problem

- open the map editor
- cancel the tour via the X
- cancel the modal popup

### Expected Result

Previous tour step is shown with modal overlay, i.e. the background darkens and is not clickable.

### Actual Result

Previous tour step is show, but without modal overlay, i.e. the background is normal and clickable

### PermaplanT version

738-allow-continue-tour

### Operating System

Windows

### Browser

Microsoft Edge

### Versions of other relevant software/extensions

_No response_

### Additional info/logs

_No response_

### PR DESCRIPTION
**Pull request by ThorbenStaufer**
User will be asked on cancellation, if they really want to complete the tour. Alternatively they can choose to continue the tour the next time or revert the cancel.

Follow-up issue for a minor bug introduced in this version: #752.

Resolves #738 and Fixes #752.

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Review by markus2330 — CHANGES_REQUESTED** [review]
Thx!

On my Firefox there is not enough space for the buttons: they are a bit outside of the modal window. See also my comment in #752

**Review by 4ydan — COMMENTED** [review]
~~Maybe it is only on my machine, but I cant see the layers and the tour is stuck?~~
~~I did a database reset and reinserted the scraper data.~~
Edit:
Ah It was some bug I think when refreshing on `/maps/1` after doing a database reset, I think.
Now it works.
LGTM

**Review by 4ydan — CHANGES_REQUESTED** [review]
One thing, maybe it would be nice to use the same buttons as on the tour? The shepherd buttons. Or what do you think about that?

**Comment by markus2330** [comment]
jenkins build please

**Comment by ThorbenStaufer** [comment]
> One thing, maybe it would be nice to use the same buttons as on the tour?

It should rather be the other way around. The cancel confirmation uses the same button component that we use for the rest of the app. The introduction tour deviates from that by using their own buttons.

**Review by markus2330 — APPROVED** [review]
Looks good now, I like it.

**Review by 4ydan — APPROVED** [review]

**Pull request merged**
