### PR TITLE
[WIP] Caching cargo

### PR DESCRIPTION
**Pull request by 4ydan**
Working on caching [cargo home](https://doc.rust-lang.org/cargo/guide/cargo-home.html) to var/cache/rust

## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [ ] The PR is rebased with current master.
- [ ] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by 4ydan** [comment]
image

I think I dont have the permission to cache inside /var/cache/rust
I put the following volumes
```
-v /var/cache/rust/registry:/usr/local/cargo/registry \
-v /var/cache/rust/git:/usr/local/cargo/git \
````
Or is that an issue on my side? @lukashartl

**Comment by markus2330** [comment]
CI obviously shouldn't have such permissions. Let us discuss this today in the meeting. There are still a few formalities to get you onboarded. But here is not the right place to discuss this :wink:

**Comment by lukashartl** [comment]
> image
> 
> I think I dont have the permission to cache inside /var/cache/rust I put the following volumes
> 
> ```
> -v /var/cache/rust/registry:/usr/local/cargo/registry \
> -v /var/cache/rust/git:/usr/local/cargo/git \
> ```
> 
> Or is that an issue on my side? @lukashartl

Why exactly do you want to use `/var/cache/rust`? You could just use a named/unnamed docker volume instead of a bind mount 😄

**Comment by 4ydan** [comment]
I want to cache between all jobs, outside of the job directory. Markus suggested `/var/cache/rust`. Good idea, can try named volumes, but not sure if I can create one.

**Pull request closed without merging**
