### PR TITLE
479 translate height&spread in scraper to enum values

### PR DESCRIPTION
**Pull request by temmey**
## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [x] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [x] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [x] Code is conforming to [our Architecture](/doc/architecture)
- [x] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [x] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by temmey** [comment]
The pipeline is failing because I added the translation process to the `mergeDatasets.js file, but we're not running `npm run merge:datasets`. As a result, the values are not getting translated, leading to the failure. 
So we either:
need to run `npm run merge:datasets` (and copy the necessary files too) so that the translation process can take place and the pipeline will run successfully.
OR 
I implement the translation step into the `npm run insert` step.

What do you think @markus2330  @4ydan ?

**Comment by markus2330** [comment]
1. @temmey simply run `npm run merge:datasets` once manually and then copy the new mergedDatasets.csv to Nextcloud.
2. Yvonne will then check.
3. @4ydan or I will then copy the updated file to all nodes (pr, dev and www.permaplant.net).

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
@temmey the build fails here:

```
/home/jenkins/workspace/PermaplanT_PR-692/scraper/node_modules/pg-protocol/dist/parser.js:287

        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);

                                                                                                 ^


error: invalid input value for enum plant_height: "3.5"

    at Parser.parseErrorMessage (/home/jenkins/workspace/PermaplanT_PR-692/scraper/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/jenkins/workspace/PermaplanT_PR-692/scraper/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/jenkins/workspace/PermaplanT_PR-692/scraper/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/jenkins/workspace/PermaplanT_PR-692/scraper/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by temmey** [comment]
> @temmey the build fails here:

Yes, it's the same issue I mentioned earlier:
`The pipeline is failing because I added the translation process to the mergeDatasets.js file, but we're not running npm run merge:datasets. `

**Comment by markus2330** [comment]
We are going in a circle. The CI should not merge datasets. We manually merge the datasets, CI only inserts the plants.

@temmey I am still waiting for the mergedDatasets.csv from you. Please copy to nextcloud and send the SHA-256. I'll copy it to the CI system.

**Comment by markus2330** [comment]
Thx, I am testing and then copying to the CI.

**Comment by markus2330** [comment]
I copied it, let us see if it works.

**Pull request merged**
