### PR TITLE
Fixed German common names not being used when language is set to German

### LINKED ISSUE #433: language not used correctly for plant search
When searching for plants the language displayed in the frontend should match the language the browsers language.

## Steps to Reproduce the Problem

Set your browsers settings and set the default language to english.
Go to <https://pr.permaplant.net/seeds/new> and log in.
Search for a plant like `Prunus`. The name in brackets should now be english:
image

Now set the language to german and do the same again (you might have to refresh the cache for it to load in german).
The name is brackets is still in english:
image

## Expected Result

The name in brackets should be german instead.

## Actual Result

The name in brackets is english no matter the language set in the browser.

## How to fix

When searching for plants the following will be returned from the backend:
```json
{
    "results": [
        {
            "id": 4572,
            "unique_name": "Prunus padus",
            "common_name_en": [
                "bird cherry"
            ]
        },
        {
            "id": 7000,
            "unique_name": "Prunus mume",
            "common_name_en": [
                "japanese apricot"
            ]
        },
        ...
    ],
    "page": 1,
    "per_page": 30,
    "total_pages": 13
}
```

As you can see only the `common_name_en` is returned (which is used to set the name in the brackets). You therefore need to go to the backend and extend the `PlantsSummaryDto` to include the `common_name_de` as well in the response.

In the frontend you then need to check the language. If it is german use `common_name_de` otherwise use `common_name_en`.

### PR DESCRIPTION
**Pull request by chr-schr**
This PR fixes German common names not being used when the language is set to German for the following occurences of common plant names:
- [x] Plant list
- [x] Tooltips
- [x] Selected plant details
- [x] Plant names on map
- [x] Seeds

This fixes #433 

## Basics

- [x] The PR is rebased with current master
- [x] I added a line to [changelog.md](/doc/changelog.md)
- [x] Details of what I changed are in the commit messages
- [x] References to issues, e.g. `close #X`, are in the commit messages and changelog
- [ ] The buildserver is happy

## Checklist

- [x] I fully described what my PR does in the documentation
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [x] I added automated tests or a [manual test protocol](../doc/tests/manual/protocol.md)
- [x] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [x] Code is conforming to [our Architecture](/doc/architecture)
- [x] Code is conforming to [our Guidelines](/doc/guidelines)
- [x] Code is consistent to [our Design Decisions](/doc/decisions)
- [ ] Exceptions to any guidelines are documented

## First Time Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I am using [Tailwind CSS Linting](https://tailwindcss.com/blog/introducing-linting-for-tailwindcss-intellisense)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] I've read through the whole documentation
- [ ] I've checked conformity to guidelines
- [ ] I've checked conformity to requirements
- [ ] I've checked that the requirements are tested

### CODE REVIEW

**Comment by markus2330** [comment]
CI unfortunately fails

**Review by hatchla — APPROVED** [review]
- [ ] I've tested the code
- [x] I've read through the whole code
- [x] I've read through the whole documentation
- [x] I've checked conformity to guidelines
- [ ] I've checked conformity to requirements
- [x] I've checked that the requirements are tested

**Comment by chr-schr** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
Excellent work! :heart:

**Pull request merged**
