### PR TITLE
Feature/334 toolbar integration

### PR DESCRIPTION
**Pull request by absurd-turtle**
## Basics

- [x] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by absurd-turtle** [comment]
This PR builds upon #244 and #308. So it needs to be merged after those.

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
jenkins build please

**Review by Bushuo — CHANGES_REQUESTED** [review]
Nice work :) Also looks great.
I just added a few comments that I think need to be addressed.

I noticed that on undo, the layer is always reset to the `Base` layer. I will mention it in the refactor issue again, so we can address it there.

**Comment by markus2330** [comment]
> This PR builds upon https://github.com/ElektraInitiative/PermaplanT/pull/244 and https://github.com/ElektraInitiative/PermaplanT/pull/308. So it needs to be merged after those.

Both are merged now. This PR needs a rebase.

**Review by markus2330 — APPROVED** [review]
Great progress, needs rebase though. Is undo/redo integration within scope of this PR?

**Comment by markus2330** [comment]
jenkins build please

**Review by Bushuo — APPROVED** [review]

**Comment by markus2330** [comment]
jenkins build please

**Pull request merged**
