### PR TITLE
Send email when master fails

### PR DESCRIPTION
**Pull request by 4ydan**
#109 

## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.

## Checklist

- [x] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [x] I fully described what my PR does in the documentation
      (not in the PR description)
- [x] I fixed all affected documentation
- [] I fixed all affected decisions
- [] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by 4ydan** [comment]
I copied the code from the libelektra pipeline. Its a more generic approach without the exception wrapping. Maybe this can be done in the future, when its needed.
image

**Comment by fel115** [comment]
> I copied the code from the libelektra pipeline. Its a more generic approach without the exception wrapping. Maybe this can be done in the future, when its needed. image

I had the same, issue. Have you done any changes to the email config in Jenkins? I think there is no smtp server configurated.

**Comment by 4ydan** [comment]
> I had the same, issue. Have you done any changes to the email config in Jenkins? I think there is no smtp server configurated.
No, I havent touched any configuration/plugins/settings in Jenkins.

**Comment by markus2330** [comment]
Thanks for the PR!

> Its a more generic approach without the exception wrapping. Maybe this can be done in the future, when its needed.

What can be done if it is already a more generic approach?

**Comment by lukashartl** [comment]
> @lukashartl do you know why SMTP setup works for Elektra but not for PermaplanT?

I just checked the smtp configuration of Jenkins and it isn't configured at all.

Are you sure it is working for libelektra build jobs? It looks to me like it isn't configured at all.

I'll configure it later and verify that sending is actually possible.

**Comment by markus2330** [comment]
> Are you sure it is working for libelektra build jobs? It looks to me like it isn't configured at all.

I got 8 emails about broken master from libelektra today :wink: 

> I'll configure it later and verify that sending is actually possible.

Thx!

**Comment by lukashartl** [comment]
> > Are you sure it is working for libelektra build jobs? It looks to me like it isn't configured at all.
> 
> I got 8 emails about broken master from libelektra today wink

Ahh. The "normative force of the factual" :cat: Can you please forward one EML file (with all headers) that you received today :) Just need to check some headers :)

**Comment by lukashartl** [comment]
@markus2330 I've configured the mail plugin and checked with the test-mail-feature. Can you please verify :smile:

**Comment by markus2330** [comment]
I didn't get an email yet.

@4ydan please rebase this PR.

**Comment by markus2330** [comment]
It worked now, I got my first E-Mail:

```
Build PermaPlanT-Folder/PermaplanT/master:292 failed.
Url: https://build.libelektra.org/job/PermaPlanT-Folder/job/PermaplanT/job/master/292/display/redirect
Reason: hudson.AbortException: script returned exit code 1

Changes: https://build.libelektra.org/job/PermaPlanT-Folder/job/PermaplanT/job/master/292/display/redirect?page=changes
* 863fec3 - gabriel.kitzberger - simply heatmap returning matrix of 0.5
* 0db085b - gabriel.kitzberger - only calculate score for intersection wi
* f3e4200 - gabriel.kitzberger - update utoipa API doc
* ba0839a - gabriel.kitzberger - move heatmap to plant_layer
* fde4b78 - gabriel.kitzberger - add rustdoc
* 0eaff84 - gabriel.kitzberger - return image from heatmap endpoint, thro
* 81ecd3a - gabriel.kitzberger - fix clippy errors
* c146127 - gabriel.kitzberger - set geometry of map in frontend
* 5a75959 - gabriel.kitzberger - rename map_geom field to geometry
* bc75d9c - gabriel.kitzberger - fix tests by adding geometry to maps
* 7a0fe79 - gabriel.kitzberger - add test for heatmap
* 878e39e - gabriel.kitzberger - fix error in frontend
* fbe0f5f - gabriel.kitzberger - use bounding box and granularity to calc
* b0f9ce4 - gabriel.kitzberger - add colors to heatmap, fix index out of 
* 1098e1f - gabriel.kitzberger - add more detailed heatmap tests
* 9530eba - gabriel.kitzberger - fix clippy errors
* 3a86842 - gabriel.kitzberger - add score based on plants relation on la
* c839a35 - gabriel.kitzberger - refactor SQL queries and add better doc
* c8204ef - gabriel.kitzberger - fix tests and add negative test
* 0b5c826 - gabriel.kitzberger - add heatmap to changelog
* e4e0052 - gabriel.kitzberger - swap coordinate system to be (0,0) at to
* fd28fba - gabriel.kitzberger - adjust heatmap down.sql
* e9070da - gabriel.kitzberger - add test protocol for manual test to doc
* 6ca9089 - gabriel.kitzberger - update test protocol
* b555522 - gabriel.kitzberger - update test protocol according to sugges
* fb6c459 - gabriel.kitzberger - update frontend according to suggestions
* aaa1919 - gabriel.kitzberger - update heatmap sql according to suggesti
* c012c33 - gabriel.kitzberger - add more detailed heatmap endpoint descr
* f302321 - gabriel.kitzberger - use integers instead of floats for bound
* 0df1e8e - gabriel.kitzberger - improve rustdoc error message on heatmap
* 7f7357a - gabriel.kitzberger - improve rustdoc error message on heatmap
* 21235f9 - gabriel.kitzberger - add doc about how to update the schema.p
* cd9e36a - gabriel.kitzberger - fix mdbook error
* 35078f2 - gabriel.kitzberger - add doc about the coordinate system
* bd2d722 - gabriel.kitzberger - move coordinate system doc to solution
* 439ba82 - gabriel.kitzberger - allow for updating the maps geometry
* 1646929 - gabriel.kitzberger - change values in SQL to floats
* a6ee00f - gabriel.kitzberger - change from brown to grey for low scores
* 934edc6 - gabriel.kitzberger - fix clippy errors
* 652904e - gabriel.kitzberger - set geometry of UpdateMap as Option in t

Logs: [...truncated 3460 lines...]
+ sudo /usr/local/bin/permaplant-deploy.sh dev /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master
+ INSTANCE_PATH=/opt/permaplant/dev
+ BACKEND_BINARY=/home/jenkins/workspace/maPlanT-Folder_PermaplanT_master/backend/target/release/backend
+ SERVICE=permaplant-dev
+ [[ ! -d /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master ]]
+ [[ ! -d /opt/permaplant/dev ]]
+ cd /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master/backend
+ LC_ALL=C
+ diesel --version
diesel 2.0.1
+ cd /home/jenkins/workspace/maPlanT-Folder_PermaplanT_master/backend
+ LC_ALL=C
+ diesel migration run --locked-schema
Running migration 2023-07-03-165000_heatmap
Failed to run 2023-07-03-165000_heatmap with: column "geometry" of relation "maps" contains null values
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
```

**Pull request merged**
