### PR TITLE
Open map editor through map overview

### LINKED ISSUE #390: Open map editor through map overview
A registered user can open a map by clicking on it in their map overview list.

### PR DESCRIPTION
**Pull request by ThorbenStaufer**
The map cards in the map overview page now link the user to the map editor with the respective map id in the URL.
Resolves #390.

## Basics

- [X] Details of what you changed are in commit messages.
- [X] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.
- [X] The PR is rebased with current master.

## Checklist

- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Review by absurd-turtle — APPROVED** [review]
LGTM

Small thing I noticed when clicking through is that it needs a refresh after creating the map, for the new map to be listed.

**Comment by ThorbenStaufer** [comment]
> Small thing I noticed when clicking through is that it needs a refresh after creating the map, for the new map to be listed.

It doesn't neccessarily need to be a reload. For me it also worked in the past waiting for a few seconds (~30) to have it appear. By now they show up instantly and I don't know what could be the cause of that. Maybe it is linked to the first map in the database?

**Comment by absurd-turtle** [comment]
@ThorbenStaufer I suggest to hide the button in the Navbar when the user is not logged in.

**Comment by ThorbenStaufer** [comment]
> I suggest to hide the button in the Navbar when the user is not logged in.

Thanks for the input, will do that.

**Review by markus2330 — APPROVED** [review]
Works great, I love it.

**Comment by ThorbenStaufer** [comment]
jenkins build please

**Comment by markus2330** [comment]
Please rebase.

**Comment by markus2330** [comment]
jenkins build please

**Comment by markus2330** [comment]
```
[warn] src/config/i18n/de/index.ts
[warn] src/config/i18n/en/index.ts
[warn] Code style issues found in 2 files. Forgot to run Prettier?
```

**Pull request merged**
