### PR TITLE
Release/0.3.2

### PR DESCRIPTION
**Pull request by markus2330**
## Basics

- [x] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [ ] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed the introduction tour
- [ ] I wrote migrations in a way that they are compatible with already present data
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](https://github.com/ElektraInitiative/PermaplanT/blob/master/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by markus2330** [comment]
@Bushuo or @absurd-turtle can you verify if the npm audit fix was applied correctly?

**Comment by Bushuo** [comment]
> @Bushuo or @absurd-turtle can you verify if the npm audit fix was applied correctly?

What was the output of `npm audit`?
I can't check for myself right now.

**Comment by markus2330** [comment]
`npm audit fix` was not able to fix it by itself, so I also changed node_modules/simple-update-notifier to version `^2.0.0` manually.

@Bushuo which parts are influenced by simple-update-notifier? Should we retest some parts?

> What was the output of npm audit?

The output of `npm audit` now is `found 0 vulnerabilities`.

Before it was

```
tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
fix available via `npm audit fix`
node_modules/tough-cookie

word-wrap  <1.2.4
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
fix available via `npm audit fix`
node_modules/word-wrap

4 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix
```

**Comment by Bushuo** [comment]
I need to check myself how those packages are used.
Sometimes those vulnerabilities are not really vulnerabilities in the context of an application that is compiled and shipped.
https://overreacted.io/npm-audit-broken-by-design/

**Comment by Bushuo** [comment]
Regarding those vulerabilities.

The packages depending on semver use it to parse the package.json and are all dev dependencies.
So I would not update semver.

though-cookie is only used by jsdom which we use for unit testing. So this is not a vulnerability of production code.

word-wrap is also only used by storybook build tools or eslint. Both not production code.

```
# npm audit report

semver  <=5.7.1 || 6.0.0 - 6.3.0 || 7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/@babel/register/node_modules/semver
node_modules/@storybook/cli/node_modules/semver
node_modules/@storybook/core-server/node_modules/semver
node_modules/@storybook/manager-api/node_modules/semver
node_modules/@typescript-eslint/eslint-plugin/node_modules/semver
node_modules/@typescript-eslint/typescript-estree/node_modules/semver
node_modules/@typescript-eslint/utils/node_modules/semver
node_modules/jest-snapshot/node_modules/semver
node_modules/normalize-package-data/node_modules/semver
node_modules/semver
node_modules/simple-update-notifier/node_modules/semver
node_modules/ts-jest/node_modules/semver
  simple-update-notifier  1.0.7 - 1.1.0
  Depends on vulnerable versions of semver
  node_modules/simple-update-notifier

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
fix available via `npm audit fix`
node_modules/tough-cookie

word-wrap  <1.2.4
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
fix available via `npm audit fix`
node_modules/word-wrap

4 moderate severity vulnerabilities


root@8691b89cb80c:/workspaces/PermaplanT/frontend# npm why simple-update-notifier
simple-update-notifier@1.1.0 dev
node_modules/simple-update-notifier
  simple-update-notifier@"^1.0.0" from @storybook/cli@7.0.6
  node_modules/@storybook/cli
    @storybook/cli@"7.0.6" from storybook@7.0.6
    node_modules/storybook
      dev storybook@"^7.0.5" from the root project
```

**Comment by markus2330** [comment]
Thx for looking into it! :heart:

I reverted all the changes except a little one which seems harmless: 8d879d48a50b94f166d3182bf725be14c17ad802

**Review by 4ydan — APPROVED** [review]
LGTM, maybe #803, but I m not sure if thats intended functionality.

**Pull request merged**
