### PR TITLE
frontend: build all URLs through axios

### PR DESCRIPTION
**Pull request by lukashartl**
## Basics

- [ ] I added a line to [/doc/CHANGELOG.md](/doc/CHANGELOG.md)
- [x] The PR is rebased with current master.
- [x] Details of what you changed are in commit messages.
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [ ] The buildserver is happy.

## Checklist

- [ ] I have installed and I am using [pre-commit hooks](../doc/contrib/README.md#Hooks)
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added unit tests for my code
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I translated all strings visible to the user
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)
- [ ] I created left-over issues for things that are still to be done
- [ ] Code is conforming to [our Architecture](/doc/architecture)
- [ ] Code is conforming to [our Guidelines](/doc/guidelines)
      (exceptions are documented)
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

## Review

- [ ] I've tested the code
- [ ] I've read through the whole code
- [ ] Examples are well chosen and understandable

### CODE REVIEW

**Comment by lukashartl** [comment]
@ThorbenStaufer @Bushuo @absurd-turtle please verify 😄 

/cc @markus2330

**Comment by ThorbenStaufer** [comment]
Can't test on [pr.permaplant.net](https://pr.permaplant.net) since the `getLayers` API call wasn't updated and is the reason the map editor crashed mid initialization.

**Comment by lukashartl** [comment]
I've updated the PR so that all URLs are built with axios. Together with the BASE_API = `/`, this could actually work :)

**Comment by markus2330** [comment]
jenkins build please

**Comment by ThorbenStaufer** [comment]
jenkins build please

**Review by ThorbenStaufer — APPROVED** [review]
I can confirm, changes work and map editor is now reachable on deployed site.

**Comment by lukashartl** [comment]
@ThorbenStaufer can you also verify whether local setup works :)

**Comment by ThorbenStaufer** [comment]
Local also works 👍

**Review by Bushuo — APPROVED** [review]
Nice one, did not know about axios.getUri.

**Comment by lukashartl** [comment]
🚀 🚀 🚀

**Comment by markus2330** [comment]
Thank you so much, great to have this fixed 🚀 🚀 🚀

**Pull request merged**
