### PR TITLE
ci: pr, dev, prod

### PR DESCRIPTION
**Pull request by lukashartl**
## Basics

- [x] Details of what you changed are in commit messages
      (first line should have `module: short statement` syntax)
- [x] References to issues, e.g. `close #X`, are in the commit messages.
- [x] The buildserver is happy.
- [x] The PR is rebased with current master.

## Checklist

- [ ] I added unit tests for my code
- [ ] I fully described what my PR does in the documentation
      (not in the PR description)
- [ ] I fixed all affected documentation
- [ ] I fixed all affected decisions
- [ ] I added code comments, logging, and assertions as appropriate
- [ ] I mentioned [every code or binary](/.reuse/dep5) not directly written or done by me in [reuse syntax](https://reuse.software/)

## Review

- [ ] Documentation is conforming to [our Documentation Guidelines](/doc/documentation.md)
- [ ] Examples are well chosen and understandable
- [ ] Code is conforming to our Coding Guidelines
- [ ] Code is consistent to [our Design Decisions](/doc/decisions)

### CODE REVIEW

**Comment by lukashartl** [comment]
@markus2330 this makes the pipeline work again as a consequence of the split of PR and Dev

**Comment by markus2330** [comment]
Thank you for the PR!

So this is only a temporary fix? Documentation is not updated, so it is quite unclear what the wanted change is. We said we won't add a boolean but will have another pipeline for production builds. Imho, this is a much cleaner separation.

**Comment by lukashartl** [comment]
Yesterday in the meeting, we said that it is also okay to stay with one Jenkinsfile as long as there are two jobs in Jenkins.

Pls merge for dev and pr to work correctly again.

Will do Prod next, but still have to check how we can use the artefacts from the general pipeline for deploying (e.g. not doing a full release build if we already have a fully functioning master build).

I'll see if I can reuse the jenkinsfile or make a separate one where I download the artefacts from the main job.

**Comment by markus2330** [comment]
Yes, one Jenkinsfile is okay (or actually better) but two is also not a big problem. Currently there is a duplication anyway.

**Pull request merged**
