### PR TITLE
refactor(pricing): improvements to the translation structure

### PR DESCRIPTION
**Pull request by Bushuo**
This should fix the errors with the `t` function.
Please consider using this translation structure.

### CODE REVIEW

**Comment by markus2330** [comment]
We merge this after the release today. For now a very short explanation of the 4 variants on the landing page is enough.

**Comment by Bushuo** [comment]
> We merge this after the release today. For now a very short explanation of the 4 variants on the landing page is enough.

I meant that Thorben should merge this branch into his. 
It is basically my review, with the things I would change.
With GitHub comments alone it would have been complicated.

**Review by ThorbenStaufer — APPROVED** [review]

**Comment by markus2330** [comment]
@Bushuo can we merge some parts here also into master?

Is the problem described in #300 maybe related?

**Comment by markus2330** [comment]
> I meant that Thorben should merge this branch into his.
> It is basically my review, with the things I would change.
> With GitHub comments alone it would have been complicated.

Great to see that you help each other. You can also directly push fixes to other branches but creating PRs targeting other branches is of course fine, too. My comment was about that the whole pricing feature is not relevant to the release anymore, I should have probably said that more clearly.

**Comment by Bushuo** [comment]
@markus2330 No this is a different bug. I already have a solution.

**Pull request merged**
